### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by kmcgill88** [arthurdenner/theme_mode_handler#6]
Any intentions on migrating this to null safety anytime soon? 😄

**Comment by arthurdenner** [comment]
Hi @kmcgill88! 👋🏽 

Thanks for reaching out about this.

As a note, I'm not working with Flutter and Dart every day, so I'm not fully aware of the changes - I'm trying to catch-up after Flutter Engage.

In any case, I've started a migration to null-safety under the branch [feat/null-safety](https://github.com/arthurdenner/theme_mode_handler/pull/new/feat/null-safety) and I opened a draft PR (#7).

I think all the code has been migrated successfully but some tests are failing.

I'll try to look into this soon and I appreciate help with a review and suggestions for improvements and fixes if you can check the PR.

**Comment by arthurdenner** [comment]
null-safety support is released in the version `3.0.0`. Let me know if you face any issues with it!
