### ISSUE TITLE
How to start an app straight in the light theme?

### ISSUE THREAD

**Issue by asavchuk** [arthurdenner/theme_mode_handler#8]
Let's suppose the `darkTheme` and `theme` properties are defined, and since the theme property defaults to ThemeMode.system, then how to start an app straight in the light theme?

**Comment by arthurdenner** [comment]
Hi @asavchuk! 👋🏽 

I just noticed this is not very well-documented in the README but you can provide a `defaultTheme` to `ThemeModeHandler`.

I suppose you can pass `ThemeMode.light` to it and your app will use it by default in case there's no preference set yet.

Please let me know if that works for you or if you find encounter any issues.

**Comment by asavchuk** [comment]
Hi @arthurdenner that's exactly what I was looking for. Thanks.
